### ISSUE TITLE
What does it actually install?

### ISSUE THREAD

**Issue by gaia** [clcain/sgx-auto-install#1]
Does it install https://github.com/intel/linux-sgx-driver or  ??

Would you mind elaborating a bit on what you've done to get it running on Debian 10?

thank you and stay healthy.

**Comment by clcain** [comment]
Hi @gaia, thanks for your interest in this repo!

There are essentially 3 components to an Intel SGX installation, the Intel SGX driver, the Intel SGX SDK, and the Intel SGX PSW. The main installation script `install.sh` will do all of those for you. The only other thing you need to do to get SGX working on your system is to enable Intel SGX in the system BIOS/UEFI (before running the installation script).

I have added more information to the README for anyone else who might find this useful!
